WebDev_MainLab/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;


namespace WebDev_MainLab.Models
{
    public class Order
    {
        public int ID { get; set; }
        [Display(Name = "Country")]
        [Required(ErrorMessage = "CountryRequired")]
        public string Country { get; set; }
        [Display(Name ="City")]
        [Required(ErrorMessage = "CityRequired")]
        public string State{ get; set; }
        [Required(ErrorMessage = "AdressRequired")]
        [MaxLength(20)]
        [Display(Name="Adress")]
        public string Adress { get; set; }
        [Required(ErrorMessage = "AdressRequired")]
        [MaxLength(20, ErrorMessage = "NameLength")]
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "AdressRequired")]
        [MaxLength(20, ErrorMessage = "SurnameLength")]
        [Display(Name = "Surname")]
        public string Surname { get; set; }
        public string UserID { get; set; }
        public double TotalPrice { get; set; }

    }
}

WebDev_MainLab/Controllers/OrdersController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebDev_MainLab.Data;
using WebDev_MainLab.Models;
using WebDev_MainLab.Attributes;
using Microsoft.AspNetCore.Authorization;

namespace WebDev_MainLab.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        public JsonResult getCountries()
        {
            var list = _context.Country.ToList();
            return Json(new SelectList(list, "Name", "Name"));
        }

        public JsonResult getStates(string countryName)
        {
            var country = _context.Country.FirstOrDefault(x => x.Name == countryName);
            var list = _context.State.Where(x => x.CountryID == country.ID).ToList();
            return Json(new SelectList(list, "Name", "Name"));
        }

        [Authorize]
        [HttpGet]
        public IActionResult Profile()
        {
            var name = User.Identity.Name;
            var userID = _context.getUser(name).Id;
            var profile = new ProfileViewModel()
            {
                Name = name,
                TotalSpend = 0,
                Items = new List<CartLine>(),
                OrdersList = _context.Order.Where(x => x.UserID == userID).ToList()
            };
            foreach (var order in profile.OrdersList)
            {
                var items = _context.OrdersItems.Where(x => x.OrderId == order.ID).ToList();
                foreach (var item in items)
                {
                    profile.Items.Add(new CartLine()
                    { MyItem = _context.getByID(item.GoodsId),
                        Quantity = item.Quantity
                    });
                }
                profile.TotalSpend += order.TotalPrice;
            }
            
            return View(profile);

        }
       // GET: Orders/Create
        [CartNotEmpty]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        [CartNotEmpty]
        public IActionResult Create([Bind("Country,State,Adress,Name,Surname")] Order order)
        {
            if (ModelState.IsValid)
            {
                var user = _context.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
                order.UserID = user.Id;
                HttpContext.Session.Set("Order", order);

                return View("OrderView", order);
            }
            return View(order);
        }
                
    }
}

WebDev_MainLab/Controllers/PayController.cs
using System;
using System.Collections.Generic;
using WebDev_MainLab.Attributes;
using WebDev_MainLab.Models;
using Microsoft.AspNetCore.Mvc;
using WebDev_MainLab.Data;
using Microsoft.Extensions.Localization;

namespace WebDev_MainLab.Controllers
{
    public class PayController : Controller
    {
        private readonly ApplicationDbContext _context;
        

        public PayController(ApplicationDbContext context)
        {
            _context = context;
           
        }

        public IActionResult Index()
        {
            return View();
        }

        [OrderExist]
        public IActionResult Card()
        {
            return View();
        }

        [HttpPost]
        [OrderExist]
        public IActionResult Create([Bind("CardNumber, OwnerName, OwnerSurname,ValidDateMonth, ValidDateYear, Code")]CreditCard creditCard)
        {
            if (ModelState.IsValid)
            {
                var order = HttpContext.Session.Get<Order>("Order");
                var cart = HttpContext.Session.Get<Cart>("Cart");
                order.TotalPrice = cart.ComputeTotalValue();

                int orderID = _context.AddOrder(order);
                
                _context.AddOrderItems(orderID, cart.Lines);

                TempData["message"] = "message";

                HttpContext.Session.SetNull("Cart");
                HttpContext.Session.SetNull("Order");

                return RedirectToAction("Index", "Home");

            }
            return View("Card", creditCard);
        }
    }
}

WebDev_MainLab/Views/Pay/Card.cshtml
@model WebDev_MainLab.Models.CreditCard

@{
    ViewData["Title"] = "Card";
}

<h4>CreditCard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="CardNumber" class="control-label"></label>
                <input asp-for="CardNumber" class="form-control" />
                <span asp-validation-for="CardNumber" class="text-danger"></span>
            </div>

            <div class="form-group" style="display:inline-flex">
                <span>
                    <label asp-for="OwnerName" class="control-label"></label>
                    <input asp-for="OwnerName" class="form-control" />
                    <span asp-validation-for="OwnerName" class="text-danger"></span>
                </span>
                <span>
                    <label asp-for="OwnerSurname" class="control-label"></label>
                    <input asp-for="OwnerSurname" class="form-control" />
                    <span asp-validation-for="OwnerSurname" class="text-danger"></span>
                </span>
            </div>
            <label class="control-label"> Valid Thru</label>
            <div class="form-group" style="display:flex">
                <span>
                    <input asp-for="ValidDateMonth" class="form-control" style="width:80px" />
                    <span asp-validation-for="ValidDateMonth" class="text-danger"></span>
                </span>
                <span>
                    <input asp-for="ValidDateYear" class="form-control" style="width:80px" />
                    <span asp-validation-for="ValidDateYear" class="text-danger"></span>
                </span>
            </div>

            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" style="width:80px"/>
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebDev_MainLab/Views/Pay/Index.cshtml
@inject IViewLocalizer Localizer;
<h2>@Localizer["choose"]:</h2>

<link rel="stylesheet" href="~/css/site.css" />
<div class="payment">
    <input type="submit" value=@Localizer["card"] id="Card" class="btn btn-default" />
    <input type="submit" value="WebMoney" id="Money" class="btn btn-default" />
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $('#Card').on("click", function () {
        var url = '@Url.Action("Card", "Pay")';
        window.location.href = url;
    });
</script>

WebDev_MainLab/Views/Pay/OrderView.cshtml
@model WebDev_MainLab.Models.OrderViewModel

<h2>Order</h2>

<dl class="res-view">
    <dt>
        Name : 
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt>
        Surname : 
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Surname)
    </dd>
    <dt>
        Country : 
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Country)
    </dd>
    <dt>
        City  :
    </dt>
    <dd>
        @Html.DisplayFor(model => model.City)
    </dd>
    <dt>
        Adress :
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Adress)
    </dd>
    <dt>
        Card :
    </dt>
    <dd>
        @Html.DisplayFor(model => model.CardNumberFirst) XXXX XXXX @Html.DisplayFor(model => model.CardNumberLast)
    </dd>
</dl>